### PR TITLE
Reduce Docker image size

### PR DESCRIPTION
**Pull request by dmke**
By using Alpine instead of Ubuntu, the resulting image is around 110 MB smaller:

    $ docker images
    REPOSITORY       TAG      CREATED         SIZE
    unms-exporter    alpine   3 seconds ago   20MB
    unms-exporter    ubuntu   5 minutes ago   132MB

Some savings are due to building with `-ldflags="-s -w"` (strip binary), and `-trimpath` (remove builder path prefixes).

We could save 5 MB more by using `FROM scratch` instead of Alpine, but then handling of timezone and CA certificate files becomes a hassle.

### CODE REVIEW

**Review by mraerino — DISMISSED** [review]
cool, that makes sense. Thanks!

**Comment by mraerino** [comment]
give me a sec to fix the CI flow for external contributions

**Comment by mraerino** [comment]
@dmke would you mind merging main into your branch so the CI can run?

**Comment by dmke** [comment]
Done.

**Pull request merged**
